version: '1.0'
services:
  rabbitmq:
    image: rabbitmq-custom:latest
    build: rabbitmq-conf/
    ports:
    - '5672:5672'
    - '15672:15672'

  rmq-producer:
    image: rmq-producer:latest
    build: rmq-producer/
    ports:
    - '8080:8080'

  rmq-consumer:
    image: rmq-consumer:latest
    build: rmq-consumer/
