version: '1.0'
services:
  activemq:
    image: rmohr/activemq:5.15.9
    ports:
    - '61616:61616'
    - '8161:8161'

  amq-producer:
    image: amq-producer:latest
    build: amq-producer/
    ports:
    - '8082:8082'

  amq-consumer:
    image: amq-consumer:latest
    build: amq-consumer/

  amq-consumer-2:
    image: amq-consumer-2:latest
    build: amq-consumer-2/